name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: prod
    steps:
      - uses: actions/checkout@v2

      - name: Cache mix modules
        uses: actions/cache@v1
        env:
          cache-name: cache-mix-modules
        with:
          path: deps # mix cache files are stored in `deps` in the root of the project folder
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-v1

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: '24.0'
          elixir-version: '1.12.3'

      - name: Install Elixir Dependencies
        run: mix deps.get --only prod

      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "16.3.0"

      - name: Cache npm modules
        uses: actions/cache@v1
        env:
          cache-name: cache-npm-modules
        with:
          path: assets/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-v1

      - name: Install NPM Dependencies
        working-directory: ./assets
        run: npm install


      - name: Compile Elixir
        run: MIX_ENV=prod mix compile

      - name: Compile assets
        run: mix assets.deploy
          
      - name: Build Mix Release
        run: MIX_ENV=prod mix release --version ${{ github.sha }}

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "_build/prod/data_works-${{ github.sha }}.tar.gz"
          target: "/tmp"

      - name: Extract release command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p data_works
            mkdir -p data_works/releases
            mkdir -p data_works/releases/${{ github.sha }}
            tar -xzf /tmp/_build/prod/data_works-${{ github.sha }}.tar.gz --directory ~/data_works/releases/${{ github.sha}}/
            cd data_works/
            echo ${{ secrets.SERVICE_TOKEN }} | doppler configure set token --silent --scope ./
            ./data_works stop
            ln -sfT ~/data_works/releases/${{ github.sha }}/bin/data_works ~/data_works/data_works
            ./data_works version
            doppler run -- ./data_works daemon
